#ifndef XMEM_CONFIG_H_
#define XMEM_CONFIG_H_

#define XPAR_AXI_BRAM_0_BASEADDRESS 0x0
#define XPAR_AXI_BRAM_0_HIGHADDRESS 0xffff
#define XPAR_AXI_BRAM_1_BASEADDRESS 0xc0000000
#define XPAR_AXI_BRAM_1_HIGHADDRESS 0xc000ffff

#endif