
PACKAGECONFIG[bram] = "${RECIPE_SYSROOT}/usr/lib/libbram.a,,bram,,"
PACKAGECONFIG[common] = "${RECIPE_SYSROOT}/usr/lib/libcommon.a,,common,,"
PACKAGECONFIG[gpio] = "${RECIPE_SYSROOT}/usr/lib/libgpio.a,,gpio,,"
PACKAGECONFIG[intc] = "${RECIPE_SYSROOT}/usr/lib/libintc.a,,intc,,"
PACKAGECONFIG[uartns550] = "${RECIPE_SYSROOT}/usr/lib/libuartns550.a,,uartns550,,"